fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]
        files: "^(src/|test/|pyproject.toml)"
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [file, python]
        files: "^(src|test)/"
